# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76de56e1357778e411b3adc4739111df62df1ac0f18991572a3bd87b326f423882b1b986f5ac660dc7b1931e9dbac9f37add22ffdf750f71885363f902ec8dc4

test:
  secret_key_base: a385edfb0df974657b25061268d0474ddf6de6ca1787cdda997b95884abedcf5f9a9faa9d81ae304bc299003abdab5fdda2cea70e80a4c5e7f4878a4329ce077

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
