# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Teacher.create(
    [{
        name:"Teacher person",
        city:"Pasadena",
        state:"California",
        zip_code:"91106",
        email:"teacher@asdfa",
        phone:"626-555-5555",
        school:"Some School",
        grade:"4th and 5th",
        topics:"geology",
        class_times:"11:00 and 1:00",
        climate_change:true,
        evolution:true,
        topics_to_cover:"How evolution works",
        benefits:"Learn from a real scientist",
        requirements:"none"
    },
    {
        name:"James the Teacher",
        city:"San Jose",
        state:"California",
        zip_code:"94306",
        email:"teacher@asdfa",
        phone:"626-555-5555",
        school:"The School",
        grade:"4th and 5th",
        topics:"geology",
        class_times:"10:00",
        climate_change:true,
        evolution:true,
        topics_to_cover:"How evolution works",
        benefits:"Learn from a real scientist",
        requirements:"none"
    },
    {
        name:"Another Teacher",
        city:"Palo Alto",
        state:"California",
        zip_code:"94306",
        email:"teacher@asdfa",
        phone:"626-555-5655",
        school:"Palo Alto High",
        grade:"11th and 12th",
        topics:"physics",
        class_times:"11:00 and 1:00",
        climate_change:true,
        evolution:true,
        topics_to_cover:"How evolution works",
        benefits:"Learn from a real scientist",
        requirements:"none"
    },
    {
        name:"Some other Teacher",
        city:"Pasadena",
        state:"California",
        zip_code:"91106",
        email:"teacher@asdfa.com",
        phone:"626-555-5566",
        school:"Some School",
        grade:"4th and 5th",
        topics:"geology",
        class_times:"11:00 and 1:00",
        climate_change:true,
        evolution:false,
        topics_to_cover:"Importance of climate change",
        benefits:"Find out what it's like to be a scientist",
        requirements:"none"
    },
    {
        name:"Bob the Teacher",
        city:"Pasadena",
        state:"California",
        zip_code:"91106",
        email:"teacher@asdfa.asdf",
        phone:"626-555-5555",
        school:"Some School",
        grade:"5th",
        topics:"geology",
        class_times:"11:00 and 1:00",
        climate_change:false,
        evolution:true,
        topics_to_cover:"How evolution works",
        benefits:"Learn from a real scientist",
        requirements:"none"
    }]
)

Scientist.create(
    [{
        name:"Brian Greene",
        city:"San Jose",
        state:"California",
        zip_code:"94305",
        email:"teacher@asdfa",
        phone:"626-555-5555",
        occupation:"Instructor",
        education:"Phd",
        affiliation:"Stanford",
        specialization:"My specialization is asdfasdfa",
        climate_change:true,
        evolution:true,
        experience:"I've given talks to classes before",
        goals:"I hope to help kids get interested in science",
        availability:"mondays",
        less_than_30:true
    },
{
        name:"Kip Thorn",
        city:"Pasadena",
        state:"California",
        zip_code:"91106",
        email:"teacher@asdfa",
        phone:"626-555-5555",
        occupation:"Instructor",
        education:"PhD",
        affiliation:"Stanford",
        specialization:"My specialization is asdfasdfa",
        climate_change:true,
        evolution:true,
        experience:"I've given talks to classes before",
        goals:"I hope to help kids get interested in science",
        availability:"mondays",
        less_than_30:true
    },
    {
        name:"Mark Whatney",
        city:"Pasadena",
        state:"California",
        zip_code:"91106",
        email:"teacher@asdfa",
        phone:"626-555-5555",
        occupation:"Instructor",
        education:"Graduate Degree",
        affiliation:"Stanford",
        specialization:"My specialization is asdfasdfa",
        climate_change:true,
        evolution:true,
        experience:"I've given talks to classes before",
        goals:"I hope to help kids get interested in science",
        availability:"mondays",
        less_than_30:true
    },
    {
        name:"Bill Nye",
        city:"Pasadena",
        state:"California",
        zip_code:"91106",
        email:"teacher@asdfa",
        phone:"626-555-5555",
        occupation:"Instructor",
        education:"Bachelor's Degree",
        affiliation:"Stanford",
        specialization:"My specialization is asdfasdfa",
        climate_change:true,
        evolution:true,
        experience:"I've given talks to classes before",
        goals:"I hope to help kids get interested in science",
        availability:"mondays",
        less_than_30:true
    },
    {
        name:"Niel DeGrasse Tyson",
        city:"Pasadena",
        state:"California",
        zip_code:"91106",
        email:"teacher@asdfa",
        phone:"626-555-5555",
        occupation:"Instructor",
        education:"PhD",
        affiliation:"Stanford",
        specialization:"My specialization is asdfasdfa",
        climate_change:true,
        evolution:true,
        experience:"I've given talks to classes before",
        goals:"I hope to help kids get interested in science",
        availability:"mondays",
        less_than_30:true
    }]
)